PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT
  ?item ?name
  ?types ?type_strings
  ?lat ?lon
WHERE {
  ?item wdt:P31 ?type .
  ?type wdt:P279* wd:Q41176 .

  {
    SELECT DISTINCT
      ?item
      ?name
      (concat('["',group_concat(?type;separator='","'),'"]') AS ?types)
      (concat('["',group_concat(?type_string;separator='","'),'"]') AS ?type_strings)
      ?lat ?lon
    WHERE {
      ?item wdt:P131* wd:Q60 .
      ?item wdt:P31 ?type .

      ?item wdt:P625 ?coord .
      ?item p:P625 ?coordinate .
      ?coordinate psv:P625 ?coordinate_node .
      ?coordinate_node wikibase:geoLatitude ?lat .
      ?coordinate_node wikibase:geoLongitude ?lon .

      SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
        ?item rdfs:label ?name .
        ?type rdfs:label ?type_string
      }
    }
    GROUP BY ?item ?name ?lon ?lat
    ORDER BY ?item
  }
}
